### PR TITLE
Update to MdePkg Versions of ARM/AARCH64 Libs

### PR DESCRIPTION
**Pull request by os-d**
edk2 PR https://github.com/tianocore/edk2/pull/6048 moved some architectural pieces
from ArmPkg to MdePkg. This patch updates all platforms (& etc.) in edk2-platforms
to use the MdePkg versions of these libs.

This patch is dependent on the above edk2 merging and must not be merged before that
goes in.

This is the v2 of https://edk2.groups.io/g/devel/topic/patch_v1_0_3_update_to/108166767 as edk2-platforms has now been moved to PRs instead of the mailing list.

Diff from v1:
- Change `#include <[Arm|AArch64]/AsmMacroLib.h>` to `#include <AsmMacroLib.h>` to follow the change requested in the edk2 PR
- Drop ArmSoftFloatLib changes here as that is getting removed in a separate PR

### CODE REVIEW

**Comment by os-d** [comment]
@ardbiesheuvel here is the updated PR

**Review by hrw — COMMENTED** [review]
For SbsaQemu:

Reviewed-by: Marcin Juszkiewicz <marcin.juszkiewicz@linaro.org>

**Review by leiflindholm — APPROVED** [review]
I'm happy for this to go in, but will give others a chance to speak up.

**Review by ndhillonm — APPROVED** [review]

**Comment by os-d** [comment]
https://github.com/tianocore/edk2/pull/6048 merged, so as soon as folks as satisfied, this can go in.

**Review by hrw — APPROVED** [review]

**Review by ardbiesheuvel — APPROVED** [review]

**Comment by ardbiesheuvel** [comment]
@mdkinney @leiflindholm 

Please merge this PR. All ARM/AARCH64 builds will remain broken otherwise, and we should not wait for all code owners to sign off on this.

Also, the criteria that it claims to operate by, i.e., `Merging can be performed automatically with 1 approving review.`, seem to be met, as several code owners have already approved, but in spite of that, merging is blocked.

This is another case where maintainers need a button to simply override the CI or GitHub logic when it is not making sense.

**Review by nhivp — APPROVED** [review]

**Review by lgao4 — APPROVED** [review]

**Comment by lgao4** [comment]
@changab , @samimujawar , please approve this change to unblock the platform build failure.

**Comment by apalos** [comment]
For PlatformStandaloneMmRpmb
Acked-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>

**Review by samimujawar — APPROVED** [review]
For Platform/ARM/* and Silicon/ARM/*
These changes look good to me.

**Comment by ardbiesheuvel** [comment]
@mdkinney @leiflindholm 

Ping again. All ARM platforms are currently build-broken in edk2-platforms, and due to the GitHub PR policy changes, you are the only persons that can actually do anything about this.

Clearly, managing edk2-platforms in this manner is not ready to be rolled out, so please revert those changes so that people that work with these repositories daily can get their workflow unbroken (I suppose neither of you are actual users of edk2-platforms)

**Comment by leiflindholm** [comment]
> Clearly, managing edk2-platforms in this manner is not ready to be rolled out, so please revert those changes so that people that work with these repositories daily can get their workflow unbroken (I suppose neither of you are actual users of edk2-platforms)

Not a daily user, certainly.

We've clearly hit a pathological case for edk2-platforms which doesn't affect us on edk2 because of the use of mergify there. All the reviewers assigned by the tianocore-assign-reviewers script need to approve a PR in order to merge it. That would be nigh-unworkable if all our maintainers were super responsive (but illness, holiday, ...).

For now, unless there is some project setting to enable merging with a single approval only, we *need* to disable tianocore-assign-reviewers and go back to manual assignment.

@mdkinney @bcran

**Comment by hrw** [comment]
TBH: I prefer GitHub PR over mailing list. EDK2 with its use of wrong end-of-line markers make merging patchsets from ML painful especially compared to "git checkout origin/pr/196" command.

What we should change is "code owners" requirement.

**Comment by mdkinney** [comment]
edk2 repo is not using CODEOWNERS feature at this time.  That is what is preventing this one from being merged.  I will disable CODEOWNERS requirement setting and match edk2 settings so the use of the CODEOWNERS feature can be discussed further.

**Comment by mdkinney** [comment]
Setting has ben updated with requirements for 1 approving review.  This PR is now unblocked.

**Comment by hrw** [comment]
Thanks @mdkinney

**Pull request merged**
