### PR TITLE
Platform/RISC-V: Add PCD variables related to PCI

### PR DESCRIPTION
**Pull request by wangy566**
Pcihostbridgelib uses the general PCD variable.
    Like PcdPciBusMin PcdPciBusMax ...

These PCDs made part of generic RISC-V package itself , so that they don't need to be added for every platform in the future.

    Reviewed-by: Sunil V L <sunilvl@ventanamicro.com>
    Cc: Leif Lindholm <quic_llindhol@quicinc.com>
    Cc: Michael D Kinney <michael.d.kinney@intel.com>
    Cc: Daniel Schaefer <git@danielschaefer.me>
    Cc: Ray Ni <ray.ni@intel.com>

### CODE REVIEW

**Comment by hrw** [comment]
So #211 or #212 will add RISCV_BIT_OP_H stuff?

**Comment by wangy566** [comment]
> So #211 or #212 will add RISCV_BIT_OP_H stuff?


#211

**Comment by vlsunil** [comment]
@wangy566 : This is not correct. Both #211 and #212 have same commit to add the bit operation macro which is the reason for @hrw to ask that question. Actually please update the #200 itself with more commits to address comments instead of raising new PRs. You can force push latest changes to same branch which will reflect.

Also, I have not yet reviewed the changes. So, please don't add RB tag. These tags are not necessary with github PR based review process.

**Comment by wangy566** [comment]
> @wangy566 : This is not correct. Both #211 and #212 have same commit to add the bit operation macro which is the reason for @hrw to ask that question. Actually please update the #200 itself with more commits to address comments instead of raising new PRs. You can force push latest changes to same branch which will reflect in the PR.
> 
> Also, I have not yet reviewed the changes. So, please don't add Reviewed-by tag. These tags are not necessary with github PR based review process. Only Signed-off tag is mandatory.

okay,Thank you for reminding me. I will correct it again

**Pull request closed without merging**
